add pulled bwa for alignment and add concat task
oicr-gsi/ichorCNA pull request #7
Opened 2021-04-07 14:56 UTC by m28feng

2021-04-07 16:27 UTC, m28feng commented
retest this please

2021-04-07 17:38 UTC, m28feng commented
retest this please

2021-04-07 20:59 UTC, m28feng commented
retest this please

2021-04-08 14:11 UTC, m28feng commented
retest this please

2021-04-08 18:40 UTC, m28feng commented
retest this please

2021-04-08 21:32 UTC, m28feng commented
retest this please

2021-04-09 15:00 UTC, lheisler approved these changes
this looks good.
my understanding that will be provided two arrays of fastq files, for R1 and R2.  It will concatenate each array to a single fastq, saving with a prefix that is provided.

concatenated fastq are aligned through the bwa mem workflow

the rest is the same, providing the alignment to ichorcna instead of using an alignment provided by the olive

2021-04-09 16:05 UTC, m28feng commented
retest this please

2021-11-03 15:44 UTC, lheisler approved these changes

2021-11-04 15:23 UTC, pruzanov requested changes
I see that only minor changes are needed, the code looks good to me, not sure if you want to change calculate.sh script (it uses line count, not md5sum) under the current PR

2021-11-04 15:23 UTC, pruzanov commented on commands.txt
> +This section lists command(s) run by WORKFLOW workflow
As I mentioned elsewhere, this is a placeholder (WORKFLOW needs to be changed to ichorCNA)

2021-11-04 15:23 UTC, pruzanov commented on README.md
> + MERGE BAMS
Also, all this changes should be listed in CHANGELOG.md file

2021-11-04 20:51 UTC, bibilujan commented
@pruzanov the changes to the calculate.sh will be applied in the near future, but will move forward with this development for now as suggested by @lheisler .

2021-11-04 20:53 UTC, merged